#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
        rm -rf /opt/stout/minifi
fi

# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
        rm -rf /opt/stout/minifi
fi

if [ "$1" = "purge" ]; then
        rm -rf /opt/stout/minifi
fi
# End automatically added section

