#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
        deb-systemd-invoke stop minifi.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/minifi" ] || [ -e "/etc/init/minifi.conf" ]; then
        invoke-rc.d minifi stop || exit $?
fi
# End automatically added section
